export { deriveChangeImpact } from './planner.js';
export {
  createChangeImpactWriter,
  renderChangeImpactMarkdown,
  renderContextPlanMarkdown,
  type ChangeImpactWriter,
} from './writer.js';
export {
  CHANGE_IMPACT_MAP_VERSION,
  CONTEXT_PLAN_VERSION,
  GRAPH_DELTA_VERSION,
  type AnalysisMode,
  type CapabilityDelta,
  type ChangeImpactInput,
  type ChangeImpactMap,
  type ChangeImpactResult,
  type ChangeNeighborhood,
  type ChangedTarget,
  type CodeIntelligenceSnapshot,
  type ContextCandidate,
  type ContextCategory,
  type ContractSurfaceDelta,
  type CoverageStatus,
  type EdgeDelta,
  type EdgeDeltaKind,
  type FactProvenance,
  type GraphDelta,
  type GraphEdge,
  type GraphNode,
  type GraphNodeRole,
  type ImpactCone,
  type ImpactConeKind,
  type ImpactConfiguration,
  type ImpactUncertainty,
  type NodeDelta,
  type NodeDeltaKind,
  type PathWitness,
  type QuestionContextPlan,
  type ReviewContextPlan,
  type ReviewIntent,
  type ReviewQuestion,
  type RiskProfile,
  type SelectedContextItem,
  type SnapshotUncertainty,
  type SourceSpan,
  type SpecialistDimension,
  type StateEffectIndicator,
  type TestReachability,
  type TraversalBudget,
  type TruncationReason,
} from './types.js';
