export {
  assertQueryResultMatches,
  parseCodeIntelligenceProviderDescriptor,
  parseCodeIntelligenceQuery,
  parseCodeIntelligenceQueryResult,
  parseCodeIntelligenceRecording,
  parseCodeIntelligenceSnapshot,
  providerCompatibilityDigest,
  snapshotCompatibilityDigest,
} from './contracts.js';
export { CodeIntelligenceProviderRegistry } from './registry.js';
export {
  CODE_INTELLIGENCE_CAPABILITIES,
  CODE_INTELLIGENCE_CONTRACT_VERSION,
  CODE_INTELLIGENCE_QUERY_VERSION,
  CODE_INTELLIGENCE_RECORDING_VERSION,
  CODE_INTELLIGENCE_RESULT_VERSION,
  CODE_INTELLIGENCE_SNAPSHOT_VERSION,
  type CapabilityDeclaration,
  type CodeIntelligenceCapability,
  type CodeIntelligenceProvider,
  type CodeIntelligenceProviderDescriptor,
  type CodeIntelligenceProviderFactory,
  type CodeIntelligenceProviderRegistration,
  type CodeIntelligenceQuery,
  type CodeIntelligenceQueryResult,
  type CodeIntelligenceRecording,
  type CodeIntelligenceSnapshot,
  type CoverageStatus,
  type FactProvenance,
  type FactStatus,
  type FileCoverage,
  type FileCoverageStatus,
  type GraphEdge,
  type GraphEdgeKind,
  type GraphNode,
  type GraphNodeKind,
  type GraphNodeRole,
  type JsonPrimitive,
  type JsonValue,
  type LanguageCoverage,
  type NormalizedEdgeFact,
  type NormalizedGraphFact,
  type NormalizedNodeFact,
  type ProviderDiagnostic,
  type ProviderDistribution,
  type ProviderExtension,
  type ProviderLicense,
  type ProviderOperationStatus,
  type QueryBudget,
  type QueryResultStatus,
  type QueryTarget,
  type QueryTruncationReason,
  type RevisionSide,
  type SnapshotBuildRequest,
  type SnapshotOpenRequest,
  type SnapshotOperationResult,
  type SnapshotUncertainty,
  type SourceProvenance,
  type SourceSpan,
} from './types.js';
