name: Nested call test

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  call:
    name: Call minimal external reusable
    uses: dragoscirjan/tmp-reusable-test/.github/workflows/minimal-reusable.yml@main
